server {
    listen 80;
    listen [::]:80;

    server_name ctf.sibainu.site;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ctf.sibainu.site;

    ssl_certificate     /etc/nginx/ssl/ctf.pem;
    ssl_certificate_key /etc/nginx/ssl/ctf.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    return 444;
}